" Name:         Mogo
" Description:  Mogo theme
" Author:       Ken Zhou <kendotzhou@gmail.com>
" Maintainer:   Ken Zhou <kendotzhou@gmail.com>
" Website:      https://github.com/notken12/nvim
" License:      MIT
" Last Updated: Tue May 17 12:29:04 2022

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'mogo'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#202020', '#83a9c8', '#83a9c8', '#fe8019', '#d3869b', '#fb4934', '#fe8019', '#858585', '#252525', '#83a9c8', '#d3869b', '#fabd2f', '#d3869b', '#8ec07c', '#fb4934', '#faf1d4']
endif
if has('nvim')
  let g:terminal_color_0 = '#202020'
  let g:terminal_color_1 = '#83a9c8'
  let g:terminal_color_2 = '#83a9c8'
  let g:terminal_color_3 = '#fe8019'
  let g:terminal_color_4 = '#d3869b'
  let g:terminal_color_5 = '#fb4934'
  let g:terminal_color_6 = '#fe8019'
  let g:terminal_color_7 = '#858585'
  let g:terminal_color_8 = '#252525'
  let g:terminal_color_9 = '#83a9c8'
  let g:terminal_color_10 = '#d3869b'
  let g:terminal_color_11 = '#fabd2f'
  let g:terminal_color_12 = '#d3869b'
  let g:terminal_color_13 = '#8ec07c'
  let g:terminal_color_14 = '#fb4934'
  let g:terminal_color_15 = '#faf1d4'
endif
if get(g:, 'mogo_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
  hi FoldColumn guifg=#252525 guibg=#202020 gui=NONE cterm=NONE
  hi LineNr guifg=#858585 guibg=#202020 gui=NONE cterm=NONE
  hi Terminal guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
else
  hi Normal guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
  hi FoldColumn guifg=#252525 guibg=#202020 gui=NONE cterm=NONE
  hi LineNr guifg=#858585 guibg=#202020 gui=NONE cterm=NONE
  hi Terminal guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=NONE guibg=#252525 gui=NONE cterm=NONE
hi Conceal guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=NONE guibg=#faf1d4 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#252525 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#252525 gui=NONE cterm=NONE
hi DiffAdd guifg=#202020 guibg=#b8bb26 gui=reverse cterm=reverse
hi DiffChange guifg=#202020 guibg=#8ec07c gui=reverse cterm=reverse
hi DiffDelete guifg=#202020 guibg=#83a9c8 gui=reverse cterm=reverse
hi Directory guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#202020 guibg=#202020 gui=NONE cterm=NONE
hi ErrorMsg guifg=#83a9c8 guibg=#faf1d4 gui=reverse cterm=reverse
hi Folded guifg=#858585 guibg=#252525 gui=italic cterm=italic
hi IncSearch guifg=#35557a guibg=#faf1d4 gui=standout cterm=reverse
hi MatchParen guifg=#252525 guibg=#35557a gui=bold,reverse cterm=bold,reverse
hi ModeMsg guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#faf1d4 guibg=#252525 gui=NONE cterm=NONE
hi PmenuSbar guifg=#252525 guibg=#252525 gui=NONE cterm=NONE
hi PmenuSel guifg=#faf1d4 guibg=#35557a gui=NONE cterm=NONE
hi PmenuThumb guifg=#252525 guibg=#858585 gui=NONE cterm=NONE
hi Question guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#35557a guibg=#faf1d4 gui=reverse cterm=reverse
hi SignColumn guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#83a9c8 guibg=NONE guisp=#fb4934 gui=undercurl cterm=underline
hi SpellCap guifg=#83a9c8 guibg=NONE guisp=#fb4934 gui=undercurl cterm=underline
hi SpellLocal guifg=#83a9c8 guibg=NONE guisp=#fb4934 gui=undercurl cterm=underline
hi SpellRare guifg=#83a9c8 guibg=NONE guisp=#fb4934 gui=undercurl cterm=underline
hi StatusLine guifg=#252525 guibg=#faf1d4 gui=reverse cterm=reverse
hi StatusLineNC guifg=NONE guibg=#faf1d4 gui=reverse cterm=reverse
hi TabLine guifg=#858585 guibg=#252525 gui=NONE cterm=NONE
hi TabLineFill guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
hi TabLineSel guifg=#faf1d4 guibg=#202020 gui=NONE cterm=NONE
hi Title guifg=#faf1d4 guibg=NONE gui=bold cterm=bold
hi VertSplit guifg=#252525 guibg=NONE gui=NONE cterm=NONE
hi Visual guifg=NONE guibg=#35557a gui=NONE cterm=NONE
hi VisualNOS guifg=NONE guibg=#35557a gui=NONE cterm=NONE
hi WarningMsg guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#faf1d4 guibg=#fb4934 gui=NONE cterm=NONE
hi Boolean guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
hi Comment guifg=#858585 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#83a9c8 guibg=#faf1d4 gui=reverse cterm=reverse
hi Float guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#d3869b guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#fb4934 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#fe8019 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#b8bb26 guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#83a9c8 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#fb4934 guibg=NONE gui=bold cterm=bold
hi Type guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
hi TSConstructor guifg=#8ec07c guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi CursorIM guifg=NONE guibg=#faf1d4 gui=NONE cterm=NONE
hi TSVariable guifg=#fabd2f guibg=NONE gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#252525 gui=NONE cterm=NONE
hi ToolbarButton guifg=#fe8019 guibg=#252525 gui=bold cterm=bold
hi NormalMode guifg=#fabd2f guibg=#faf1d4 gui=reverse cterm=reverse
hi InsertMode guifg=#b8bb26 guibg=#202020 gui=reverse cterm=reverse
hi ReplaceMode guifg=#83a9c8 guibg=#202020 gui=reverse cterm=reverse
hi VisualMode guifg=#faf1d4 guibg=#fe8019 gui=NONE cterm=NONE
hi CommandMode guifg=#fb4934 guibg=#faf1d4 gui=reverse cterm=reverse
hi IndentBlanklineChar guifg=#858585 guibg=NONE gui=nocombine cterm=nocombine
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif
if has('nvim')
  hi! link TermCursor Cursor
  hi TermCursorNC guifg=#faf1d4 guibg=#858585 gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'mogo_transp_bg', 0)
    hi Normal ctermfg=230 ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=230 ctermbg=234 cterm=NONE
    hi FoldColumn ctermfg=235 ctermbg=234 cterm=NONE
    hi LineNr ctermfg=102 ctermbg=234 cterm=NONE
    hi Terminal ctermfg=230 ctermbg=234 cterm=NONE
  else
    hi Normal ctermfg=230 ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=230 ctermbg=234 cterm=NONE
    hi FoldColumn ctermfg=235 ctermbg=234 cterm=NONE
    hi LineNr ctermfg=102 ctermbg=234 cterm=NONE
    hi Terminal ctermfg=230 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi Conceal ctermfg=208 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=230 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=235 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi DiffAdd ctermfg=234 ctermbg=142 cterm=reverse
  hi DiffChange ctermfg=234 ctermbg=107 cterm=reverse
  hi DiffDelete ctermfg=234 ctermbg=110 cterm=reverse
  hi Directory ctermfg=175 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=234 ctermbg=234 cterm=NONE
  hi ErrorMsg ctermfg=110 ctermbg=230 cterm=reverse
  hi Folded ctermfg=102 ctermbg=235 cterm=italic
  hi IncSearch ctermfg=24 ctermbg=230 cterm=reverse
  hi MatchParen ctermfg=235 ctermbg=24 cterm=bold,reverse
  hi ModeMsg ctermfg=230 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=102 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=230 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=230 ctermbg=235 cterm=NONE
  hi PmenuSbar ctermfg=235 ctermbg=235 cterm=NONE
  hi PmenuSel ctermfg=230 ctermbg=24 cterm=NONE
  hi PmenuThumb ctermfg=235 ctermbg=102 cterm=NONE
  hi Question ctermfg=102 ctermbg=NONE cterm=NONE
  hi Search ctermfg=24 ctermbg=230 cterm=reverse
  hi SignColumn ctermfg=102 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=110 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=110 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=110 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=110 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=235 ctermbg=230 cterm=reverse
  hi StatusLineNC ctermfg=NONE ctermbg=230 cterm=reverse
  hi TabLine ctermfg=102 ctermbg=235 cterm=NONE
  hi TabLineFill ctermfg=230 ctermbg=234 cterm=NONE
  hi TabLineSel ctermfg=230 ctermbg=234 cterm=NONE
  hi Title ctermfg=230 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=235 ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=24 cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=24 cterm=NONE
  hi WarningMsg ctermfg=110 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=230 ctermbg=196 cterm=NONE
  hi Boolean ctermfg=175 ctermbg=NONE cterm=NONE
  hi Character ctermfg=196 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=102 ctermbg=NONE cterm=italic
  hi Constant ctermfg=175 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=196 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=230 ctermbg=NONE cterm=NONE
  hi Error ctermfg=110 ctermbg=230 cterm=reverse
  hi Float ctermfg=175 ctermbg=NONE cterm=NONE
  hi Function ctermfg=110 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=208 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=230 ctermbg=NONE cterm=NONE
  hi Include ctermfg=110 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=208 ctermbg=NONE cterm=NONE
  hi Label ctermfg=110 ctermbg=NONE cterm=NONE
  hi Number ctermfg=175 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=230 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=196 ctermbg=NONE cterm=NONE
  hi Special ctermfg=196 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=196 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=110 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=208 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=208 ctermbg=NONE cterm=NONE
  hi String ctermfg=142 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=110 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=196 ctermbg=NONE cterm=bold
  hi Type ctermfg=107 ctermbg=NONE cterm=NONE
  hi TSConstructor ctermfg=107 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=230 cterm=NONE
  hi TSVariable ctermfg=214 ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=235 cterm=NONE
  hi ToolbarButton ctermfg=208 ctermbg=235 cterm=bold
  hi NormalMode ctermfg=214 ctermbg=230 cterm=reverse
  hi InsertMode ctermfg=142 ctermbg=234 cterm=reverse
  hi ReplaceMode ctermfg=110 ctermbg=234 cterm=reverse
  hi VisualMode ctermfg=230 ctermbg=208 cterm=NONE
  hi CommandMode ctermfg=196 ctermbg=230 cterm=reverse
  hi IndentBlanklineChar ctermfg=102 ctermbg=NONE cterm=nocombine
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=230 ctermbg=102 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'mogo_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=Black ctermbg=Black cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=Black ctermbg=Black cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=White cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=Black ctermbg=LightGreen cterm=reverse
  hi DiffChange ctermfg=Black ctermbg=LightBlue cterm=reverse
  hi DiffDelete ctermfg=Black ctermbg=Red cterm=reverse
  hi Directory ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=Black cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=White cterm=reverse
  hi Folded ctermfg=Gray ctermbg=Black cterm=italic
  hi IncSearch ctermfg=DarkCyan ctermbg=White cterm=reverse
  hi MatchParen ctermfg=Black ctermbg=DarkCyan cterm=bold,reverse
  hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=White ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=White ctermbg=Black cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=Gray cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkCyan ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=Red ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=Black ctermbg=White cterm=reverse
  hi StatusLineNC ctermfg=NONE ctermbg=White cterm=reverse
  hi TabLine ctermfg=Gray ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Black cterm=NONE
  hi Title ctermfg=White ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Black ctermbg=NONE cterm=NONE
  hi Visual ctermfg=NONE ctermbg=DarkCyan cterm=NONE
  hi VisualNOS ctermfg=NONE ctermbg=DarkCyan cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=Green cterm=NONE
  hi Boolean ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Character ctermfg=Green ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Debug ctermfg=Green ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=White cterm=reverse
  hi Float ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Function ctermfg=Red ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Include ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Label ctermfg=Red ctermbg=NONE cterm=NONE
  hi Number ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Operator ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=Green ctermbg=NONE cterm=NONE
  hi Special ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=Green ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi String ctermfg=LightGreen ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Red ctermbg=NONE cterm=NONE
  hi Todo ctermfg=Green ctermbg=NONE cterm=bold
  hi Type ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi TSConstructor ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi TSVariable ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkRed ctermbg=Black cterm=bold
  hi NormalMode ctermfg=Yellow ctermbg=White cterm=reverse
  hi InsertMode ctermfg=LightGreen ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=Red ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=White ctermbg=DarkRed cterm=NONE
  hi CommandMode ctermfg=Green ctermbg=White cterm=reverse
  hi IndentBlanklineChar ctermfg=Gray ctermbg=NONE cterm=nocombine
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=White ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: base00 #202020 ~ Black # Default Background
" Color: base01 #252525 ~ Black # Lighter Background (Used for status bars, line number and folding marks)
" Color: base02 #35557a ~ DarkCyan # Selection Background
" Color: base03 #858585 ~ Gray # Comments, Invisibles, Line Highlighting
" Color: base04 #cac7bd ~ White # Dark Foreground (Used for status bars)
" Color: base05 #faf1d4 ~ White # Default Foreground, Caret, Delimiters, Operators
" Color: base06 #faf1d4 ~ White # Light Foreground (Not often used)
" Color: base07 #faf1d4 ~ White # Light Background (Not often used)
" Color: base08 #fabd2f ~ Yellow # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
" Color: base09 #d3869b ~ Cyan # Integers, Boolean, Constants, XML Attributes, Markup Link Url
" Color: base0A #8ec07c ~ LightBlue # Classes, Markup Bold, Search Text Background
" Color: base0B #b8bb26 ~ LightGreen # Strings, Inherited Class, Markup Code, Diff Inserted
" Color: base0C #fb4934 ~ Green # Support, Regular Expressions, Escape Characters, Markup Quotes
" Color: base0D #83a9c8 ~ Red # Functions, Methods, Attribute IDs, Headings
" Color: base0E #fe8019 ~ DarkRed # Keywords, Storage, Selector, Markup Italic, Diff Changed
" Color: base0F #d65d0e ~ Brown # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
" Term Colors: base00 base0D base0D base0E base09 base0C base0E base03
" Term Colors: base01 base0D base09 base08
" Term Colors: base09 base0A base0C base05
" vim: et ts=2 sw=2
