" Name:         WWDC16
" Description:  Colorful dark color scheme for Vim inspired by Apple's WWDC16 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-wwdc16-theme
" License:      MIT
" Last Updated: Fri May 13 18:48:07 2022

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'wwdc16'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#262628', '#e64547', '#42a647', '#c98351', '#296c9e', '#d24e9b', '#64878f', '#949494', '#323234', '#f84547', '#95c76f', '#efa16b', '#577590', '#8485ce', '#3f8efc', '#ffffff']
endif
if has('nvim')
  let g:terminal_color_0 = '#262628'
  let g:terminal_color_1 = '#e64547'
  let g:terminal_color_2 = '#42a647'
  let g:terminal_color_3 = '#c98351'
  let g:terminal_color_4 = '#296c9e'
  let g:terminal_color_5 = '#d24e9b'
  let g:terminal_color_6 = '#64878f'
  let g:terminal_color_7 = '#949494'
  let g:terminal_color_8 = '#323234'
  let g:terminal_color_9 = '#f84547'
  let g:terminal_color_10 = '#95c76f'
  let g:terminal_color_11 = '#efa16b'
  let g:terminal_color_12 = '#577590'
  let g:terminal_color_13 = '#8485ce'
  let g:terminal_color_14 = '#3f8efc'
  let g:terminal_color_15 = '#ffffff'
endif
if get(g:, 'wwdc16_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#949494 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#ffffff guibg=#262628 gui=NONE cterm=NONE
  hi CursorLineNr guifg=#ffffff guibg=#323234 gui=NONE cterm=NONE
  hi FoldColumn guifg=#949494 guibg=#323234 gui=NONE cterm=NONE
  hi LineNr guifg=#949494 guibg=#262628 gui=NONE cterm=NONE
  hi Terminal guifg=#ffffff guibg=#262628 gui=NONE cterm=NONE
endif
hi ColorColumn guifg=NONE guibg=#323234 gui=NONE cterm=NONE
hi Conceal guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=#ffffff guibg=#296c9e gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#323234 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#323234 gui=NONE cterm=NONE
hi DiffAdd guifg=#95c76f guibg=#262628 gui=NONE cterm=NONE
hi DiffChange guifg=#c98351 guibg=#ffffff gui=NONE cterm=NONE
hi DiffDelete guifg=#e64547 guibg=#ffffff gui=NONE cterm=NONE
hi DiffText guifg=#42a647 guibg=#ffffff gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#323234 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
hi Folded guifg=#949494 guibg=#323234 gui=italic cterm=italic
hi IncSearch guifg=#e64547 guibg=#ffffff gui=standout cterm=reverse
hi MatchParen guifg=#323234 guibg=#c98351 gui=bold,reverse cterm=bold,reverse
hi ModeMsg guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#262628 guibg=#64878f gui=NONE cterm=NONE
hi PmenuSbar guifg=#323234 guibg=#323234 gui=NONE cterm=NONE
hi PmenuSel guifg=#ffffff guibg=#c98351 gui=NONE cterm=NONE
hi PmenuThumb guifg=#323234 guibg=#c98351 gui=NONE cterm=NONE
hi Question guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#c98351 guibg=#ffffff gui=reverse cterm=reverse
hi SignColumn guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#949494 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#f84547 guibg=NONE guisp=#e64547 gui=undercurl cterm=underline
hi SpellCap guifg=#f84547 guibg=NONE guisp=#e64547 gui=undercurl cterm=underline
hi SpellLocal guifg=#f84547 guibg=NONE guisp=#e64547 gui=undercurl cterm=underline
hi SpellRare guifg=#f84547 guibg=NONE guisp=#e64547 gui=undercurl cterm=underline
hi StatusLine guifg=#64878f guibg=#ffffff gui=reverse cterm=reverse
hi StatusLineNC guifg=#64878f guibg=#262628 gui=reverse cterm=reverse
hi TabLine guifg=#262628 guibg=#262628 gui=NONE cterm=NONE
hi TabLineFill guifg=#ffffff guibg=#296c9e gui=NONE cterm=NONE
hi TabLineSel guifg=#ffffff guibg=#296c9e gui=NONE cterm=NONE
hi Title guifg=#c98351 guibg=NONE gui=bold cterm=bold
hi VertSplit guifg=#323234 guibg=#64878f gui=NONE cterm=NONE
hi Visual guifg=#296c9e guibg=#ffffff gui=reverse cterm=reverse
hi VisualNOS guifg=#ffffff guibg=#296c9e gui=NONE cterm=NONE
hi WarningMsg guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#ffffff guibg=#e64547 gui=NONE cterm=NONE
hi Boolean guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
hi Comment guifg=#949494 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#c98351 guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
hi Float guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#3f8efc guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#ffffff guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#42a647 guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#3f8efc guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#64878f guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#3f8efc guibg=NONE gui=NONE cterm=NONE
hi String guifg=#95c76f guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#e64547 guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#e64547 guibg=NONE gui=bold cterm=bold
hi Type guifg=#f84547 guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi CursorIM guifg=NONE guibg=#ffffff gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#323234 gui=NONE cterm=NONE
hi ToolbarButton guifg=#64878f guibg=#323234 gui=bold cterm=bold
hi NormalMode guifg=#949494 guibg=#ffffff gui=reverse cterm=reverse
hi InsertMode guifg=#95c76f guibg=#262628 gui=reverse cterm=reverse
hi ReplaceMode guifg=#c98351 guibg=#262628 gui=reverse cterm=reverse
hi VisualMode guifg=#296c9e guibg=#ffffff gui=reverse cterm=reverse
hi CommandMode guifg=#e64547 guibg=#ffffff gui=reverse cterm=reverse
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif
if has('nvim')
  hi! link TermCursor Cursor
  hi TermCursorNC guifg=#ffffff guibg=#949494 gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=231 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=231 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=246 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=231 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=231 ctermbg=236 cterm=NONE
    hi CursorLineNr ctermfg=231 ctermbg=237 cterm=NONE
    hi FoldColumn ctermfg=246 ctermbg=237 cterm=NONE
    hi LineNr ctermfg=246 ctermbg=236 cterm=NONE
    hi Terminal ctermfg=231 ctermbg=236 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi Conceal ctermfg=66 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=231 ctermbg=26 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=237 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi DiffAdd ctermfg=150 ctermbg=236 cterm=NONE
  hi DiffChange ctermfg=173 ctermbg=231 cterm=NONE
  hi DiffDelete ctermfg=167 ctermbg=231 cterm=NONE
  hi DiffText ctermfg=71 ctermbg=231 cterm=bold,reverse
  hi Directory ctermfg=150 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=237 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=231 cterm=reverse
  hi Folded ctermfg=246 ctermbg=237 cterm=italic
  hi IncSearch ctermfg=167 ctermbg=231 cterm=reverse
  hi MatchParen ctermfg=237 ctermbg=173 cterm=bold,reverse
  hi ModeMsg ctermfg=231 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=246 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=231 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=236 ctermbg=66 cterm=NONE
  hi PmenuSbar ctermfg=237 ctermbg=237 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=173 cterm=NONE
  hi PmenuThumb ctermfg=237 ctermbg=173 cterm=NONE
  hi Question ctermfg=246 ctermbg=NONE cterm=NONE
  hi Search ctermfg=173 ctermbg=231 cterm=reverse
  hi SignColumn ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=246 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=203 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=66 ctermbg=231 cterm=reverse
  hi StatusLineNC ctermfg=66 ctermbg=236 cterm=reverse
  hi TabLine ctermfg=236 ctermbg=236 cterm=NONE
  hi TabLineFill ctermfg=231 ctermbg=26 cterm=NONE
  hi TabLineSel ctermfg=231 ctermbg=26 cterm=NONE
  hi Title ctermfg=173 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=237 ctermbg=66 cterm=NONE
  hi Visual ctermfg=26 ctermbg=231 cterm=reverse
  hi VisualNOS ctermfg=231 ctermbg=26 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=231 ctermbg=167 cterm=NONE
  hi Boolean ctermfg=150 ctermbg=NONE cterm=NONE
  hi Character ctermfg=173 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=246 ctermbg=NONE cterm=italic
  hi Constant ctermfg=173 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=167 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=231 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=231 cterm=reverse
  hi Float ctermfg=150 ctermbg=NONE cterm=NONE
  hi Function ctermfg=71 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=37 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=231 ctermbg=NONE cterm=NONE
  hi Include ctermfg=167 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=66 ctermbg=NONE cterm=NONE
  hi Label ctermfg=71 ctermbg=NONE cterm=NONE
  hi Number ctermfg=150 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=37 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=167 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=66 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=37 ctermbg=NONE cterm=NONE
  hi String ctermfg=150 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=167 ctermbg=NONE cterm=bold
  hi Type ctermfg=203 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=231 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=237 cterm=NONE
  hi ToolbarButton ctermfg=66 ctermbg=237 cterm=bold
  hi NormalMode ctermfg=246 ctermbg=231 cterm=reverse
  hi InsertMode ctermfg=150 ctermbg=236 cterm=reverse
  hi ReplaceMode ctermfg=173 ctermbg=236 cterm=reverse
  hi VisualMode ctermfg=26 ctermbg=231 cterm=reverse
  hi CommandMode ctermfg=167 ctermbg=231 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=231 ctermbg=246 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=DarkGray cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi Conceal ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=NONE
  hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=NONE
  hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=NONE
  hi DiffText ctermfg=DarkGreen ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=Green ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Folded ctermfg=Gray ctermbg=DarkGray cterm=italic
  hi IncSearch ctermfg=DarkRed ctermbg=White cterm=reverse
  hi MatchParen ctermfg=DarkGray ctermbg=DarkYellow cterm=bold,reverse
  hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=White ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi PmenuSbar ctermfg=DarkGray ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=DarkYellow cterm=NONE
  hi PmenuThumb ctermfg=DarkGray ctermbg=DarkYellow cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkYellow ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=Red ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=DarkCyan ctermbg=White cterm=reverse
  hi StatusLineNC ctermfg=DarkCyan ctermbg=Black cterm=reverse
  hi TabLine ctermfg=Black ctermbg=Black cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi Title ctermfg=DarkYellow ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=DarkGray ctermbg=DarkCyan cterm=NONE
  hi Visual ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkRed cterm=NONE
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Debug ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Include ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=Green ctermbg=NONE cterm=NONE
  hi Operator ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=Cyan ctermbg=NONE cterm=NONE
  hi String ctermfg=Green ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkRed ctermbg=NONE cterm=bold
  hi Type ctermfg=Red ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=DarkGray cterm=NONE
  hi ToolbarButton ctermfg=DarkCyan ctermbg=DarkGray cterm=bold
  hi NormalMode ctermfg=Gray ctermbg=White cterm=reverse
  hi InsertMode ctermfg=Green ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=DarkYellow ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi CommandMode ctermfg=DarkRed ctermbg=White cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=White ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: black                rgb( 38,  38,  40)   236        Black
" Color: red                  rgb(230,  69,  71)   167        DarkRed
" Color: green                rgb( 66, 166,  71)   71         DarkGreen
" Color: yellow               rgb(201, 131,  81)   173        DarkYellow
" Color: blue                 rgb( 41, 108, 158 )   26         DarkBlue
" Color: magenta              rgb(210,  78, 155)   169        DarkMagenta
" Color: cyan                 rgb(100, 135, 143)   66         DarkCyan
" Color: white                rgb(148, 148, 148)   246        Gray
" Color: brightblack          rgb(50, 50, 52)   237        DarkGray
" Color: brightred            rgb(248,  69,  71)   203        Red
" Color: brightgreen          rgb(149, 199, 111)   150        Green
" Color: brightyellow         rgb(239, 161, 107)   216        Yellow
" Color: brightblue           rgb( 87,117,144)   69         Blue
" Color: brightmagenta        rgb(132, 133, 206)   104        Magenta
" Color: brightcyan           rgb(  63,142,252)   37         Cyan
" Color: brightwhite          rgb(255, 255, 255)   231        White
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: brightblack brightred brightgreen brightyellow
" Term Colors: brightblue brightmagenta brightcyan brightwhite
" vim: et ts=2 sw=2
