" Name:         WWDC16
" Description:  Colorful dark color scheme for Vim inspibase0D by Apple's WWDC16 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-wwdc16-theme
" License:      MIT
" Last Updated: Mon May 16 22:03:04 2022

" Generated by Colortemplate v2.2.0

set background=dark

hi clear
let g:colors_name = 'wwdc16'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 1
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link Repeat Statement
hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#1f1f1f', '#fa755f', '#fa755f', '#ffc145', '#6e7bfa', '#9fdfff', '#ffc145', '#858585', '#353535', '#fa755f', '#6e7bfa', '#f5da71', '#6e7bfa', '#df85ff', '#9fdfff', '#faf1d4']
endif
if has('nvim')
  let g:terminal_color_0 = '#1f1f1f'
  let g:terminal_color_1 = '#fa755f'
  let g:terminal_color_2 = '#fa755f'
  let g:terminal_color_3 = '#ffc145'
  let g:terminal_color_4 = '#6e7bfa'
  let g:terminal_color_5 = '#9fdfff'
  let g:terminal_color_6 = '#ffc145'
  let g:terminal_color_7 = '#858585'
  let g:terminal_color_8 = '#353535'
  let g:terminal_color_9 = '#fa755f'
  let g:terminal_color_10 = '#6e7bfa'
  let g:terminal_color_11 = '#f5da71'
  let g:terminal_color_12 = '#6e7bfa'
  let g:terminal_color_13 = '#df85ff'
  let g:terminal_color_14 = '#9fdfff'
  let g:terminal_color_15 = '#faf1d4'
endif
if get(g:, 'wwdc16_transp_bg', 0) && !has('gui_running')
  hi Normal guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
  hi CursorLineNr guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
  hi FoldColumn guifg=#353535 guibg=NONE gui=NONE cterm=NONE
  hi LineNr guifg=#858585 guibg=NONE gui=NONE cterm=NONE
  hi Terminal guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
else
  hi Normal guifg=#faf1d4 guibg=#1f1f1f gui=NONE cterm=NONE
  hi CursorLineNr guifg=#faf1d4 guibg=#1f1f1f gui=NONE cterm=NONE
  hi FoldColumn guifg=#858585 guibg=#1f1f1f gui=NONE cterm=NONE
  hi LineNr guifg=#858585 guibg=#1f1f1f gui=NONE cterm=NONE
  hi Terminal guifg=#faf1d4 guibg=#1f1f1f gui=NONE cterm=NONE
endif
hi ColorColumn guifg=NONE guibg=#353535 gui=NONE cterm=NONE
hi Conceal guifg=#ffc145 guibg=NONE gui=NONE cterm=NONE
hi Cursor guifg=NONE guibg=#faf1d4 gui=NONE cterm=NONE
hi CursorColumn guifg=NONE guibg=#353535 gui=NONE cterm=NONE
hi CursorLine guifg=NONE guibg=#353535 gui=NONE cterm=NONE
hi DiffAdd guifg=#bede48 guibg=#faf1d4 gui=reverse cterm=reverse
hi DiffChange guifg=#6e7bfa guibg=#faf1d4 gui=reverse cterm=reverse
hi DiffDelete guifg=#fa755f guibg=#faf1d4 gui=reverse cterm=reverse
hi DiffText guifg=#fa755f guibg=#faf1d4 gui=bold,reverse cterm=bold,reverse
hi Directory guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi EndOfBuffer guifg=#353535 guibg=NONE gui=NONE cterm=NONE
hi ErrorMsg guifg=#fa755f guibg=#faf1d4 gui=reverse cterm=reverse
hi Folded guifg=#858585 guibg=#353535 gui=italic cterm=italic
hi IncSearch guifg=#9fdfff guibg=#faf1d4 gui=standout cterm=reverse
hi MatchParen guifg=#353535 guibg=#356575 gui=bold,reverse cterm=bold,reverse
hi ModeMsg guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi MoreMsg guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi NonText guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Pmenu guifg=#1f1f1f guibg=#ffc145 gui=NONE cterm=NONE
hi PmenuSbar guifg=#353535 guibg=#353535 gui=NONE cterm=NONE
hi PmenuSel guifg=#faf1d4 guibg=#356575 gui=NONE cterm=NONE
hi PmenuThumb guifg=#353535 guibg=#356575 gui=NONE cterm=NONE
hi Question guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi Search guifg=#356575 guibg=#faf1d4 gui=reverse cterm=reverse
hi SignColumn guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi SpecialKey guifg=#858585 guibg=NONE gui=NONE cterm=NONE
hi SpellBad guifg=#fa755f guibg=NONE guisp=#9fdfff gui=undercurl cterm=underline
hi SpellCap guifg=#fa755f guibg=NONE guisp=#9fdfff gui=undercurl cterm=underline
hi SpellLocal guifg=#fa755f guibg=NONE guisp=#9fdfff gui=undercurl cterm=underline
hi SpellRare guifg=#fa755f guibg=NONE guisp=#9fdfff gui=undercurl cterm=underline
hi StatusLine guifg=#ffc145 guibg=#faf1d4 gui=reverse cterm=reverse
hi StatusLineNC guifg=#ffc145 guibg=#faf1d4 gui=reverse cterm=reverse
hi TabLine guifg=#1f1f1f guibg=#ffc145 gui=NONE cterm=NONE
hi TabLineFill guifg=#faf1d4 guibg=#ffc145 gui=NONE cterm=NONE
hi TabLineSel guifg=#faf1d4 guibg=#ffc145 gui=NONE cterm=NONE
hi Title guifg=#faf1d4 guibg=NONE gui=bold cterm=bold
hi VertSplit guifg=#353535 guibg=#ffc145 gui=NONE cterm=NONE
hi Visual guifg=#faf1d4 guibg=#356575 gui=reverse cterm=reverse
hi VisualNOS guifg=#faf1d4 guibg=#356575 gui=NONE cterm=NONE
hi WarningMsg guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi WildMenu guifg=#faf1d4 guibg=#9fdfff gui=NONE cterm=NONE
hi Boolean guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi Character guifg=#9fdfff guibg=NONE gui=NONE cterm=NONE
hi Comment guifg=#858585 guibg=NONE gui=italic cterm=italic
hi Constant guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi Debug guifg=#9fdfff guibg=NONE gui=NONE cterm=NONE
hi Delimiter guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Error guifg=#fa755f guibg=#faf1d4 gui=reverse cterm=reverse
hi Float guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi Function guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi Identifier guifg=#f5da71 guibg=NONE gui=NONE cterm=NONE
hi Ignore guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi Include guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi Keyword guifg=#ffc145 guibg=NONE gui=NONE cterm=NONE
hi Label guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi Number guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi Operator guifg=#faf1d4 guibg=NONE gui=NONE cterm=NONE
hi PreProc guifg=#9fdfff guibg=NONE gui=NONE cterm=NONE
hi Special guifg=#9fdfff guibg=NONE gui=NONE cterm=NONE
hi SpecialChar guifg=#9fdfff guibg=NONE gui=NONE cterm=NONE
hi SpecialComment guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi Statement guifg=#ffc145 guibg=NONE gui=NONE cterm=NONE
hi StorageClass guifg=#ffc145 guibg=NONE gui=NONE cterm=NONE
hi String guifg=#6e7bfa guibg=NONE gui=NONE cterm=NONE
hi Structure guifg=#fa755f guibg=NONE gui=NONE cterm=NONE
hi Todo guifg=#9fdfff guibg=NONE gui=bold cterm=bold
hi Type guifg=#df85ff guibg=NONE gui=NONE cterm=NONE
hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
hi CursorIM guifg=NONE guibg=#faf1d4 gui=NONE cterm=NONE
hi ToolbarLine guifg=NONE guibg=#353535 gui=NONE cterm=NONE
hi ToolbarButton guifg=#ffc145 guibg=#353535 gui=bold cterm=bold
hi NormalMode guifg=#858585 guibg=#faf1d4 gui=reverse cterm=reverse
hi InsertMode guifg=#6e7bfa guibg=#1f1f1f gui=reverse cterm=reverse
hi ReplaceMode guifg=#fa755f guibg=#1f1f1f gui=reverse cterm=reverse
hi VisualMode guifg=#ffc145 guibg=#faf1d4 gui=reverse cterm=reverse
hi CommandMode guifg=#9fdfff guibg=#faf1d4 gui=reverse cterm=reverse
if !s:italics
  hi Folded gui=NONE cterm=NONE
  hi Comment gui=NONE cterm=NONE
endif
if has('nvim')
  hi! link TermCursor Cursor
  hi TermCursorNC guifg=#faf1d4 guibg=#858585 gui=NONE cterm=NONE
endif

if s:t_Co >= 256
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=230 ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=230 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=236 ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=102 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=230 ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=230 ctermbg=234 cterm=NONE
    hi CursorLineNr ctermfg=230 ctermbg=234 cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=234 cterm=NONE
    hi LineNr ctermfg=102 ctermbg=234 cterm=NONE
    hi Terminal ctermfg=230 ctermbg=234 cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi Conceal ctermfg=214 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=230 cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=236 cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi DiffAdd ctermfg=148 ctermbg=230 cterm=reverse
  hi DiffChange ctermfg=69 ctermbg=230 cterm=reverse
  hi DiffDelete ctermfg=203 ctermbg=230 cterm=reverse
  hi DiffText ctermfg=203 ctermbg=230 cterm=bold,reverse
  hi Directory ctermfg=69 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=236 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=203 ctermbg=230 cterm=reverse
  hi Folded ctermfg=102 ctermbg=236 cterm=italic
  hi IncSearch ctermfg=117 ctermbg=230 cterm=reverse
  hi MatchParen ctermfg=236 ctermbg=24 cterm=bold,reverse
  hi ModeMsg ctermfg=230 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=102 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=230 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=234 ctermbg=214 cterm=NONE
  hi PmenuSbar ctermfg=236 ctermbg=236 cterm=NONE
  hi PmenuSel ctermfg=230 ctermbg=24 cterm=NONE
  hi PmenuThumb ctermfg=236 ctermbg=24 cterm=NONE
  hi Question ctermfg=102 ctermbg=NONE cterm=NONE
  hi Search ctermfg=24 ctermbg=230 cterm=reverse
  hi SignColumn ctermfg=102 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=102 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=203 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=203 ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=214 ctermbg=230 cterm=reverse
  hi StatusLineNC ctermfg=214 ctermbg=230 cterm=reverse
  hi TabLine ctermfg=234 ctermbg=214 cterm=NONE
  hi TabLineFill ctermfg=230 ctermbg=214 cterm=NONE
  hi TabLineSel ctermfg=230 ctermbg=214 cterm=NONE
  hi Title ctermfg=230 ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=236 ctermbg=214 cterm=NONE
  hi Visual ctermfg=230 ctermbg=24 cterm=reverse
  hi VisualNOS ctermfg=230 ctermbg=24 cterm=NONE
  hi WarningMsg ctermfg=203 ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=230 ctermbg=117 cterm=NONE
  hi Boolean ctermfg=69 ctermbg=NONE cterm=NONE
  hi Character ctermfg=117 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=102 ctermbg=NONE cterm=italic
  hi Constant ctermfg=69 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=117 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=230 ctermbg=NONE cterm=NONE
  hi Error ctermfg=203 ctermbg=230 cterm=reverse
  hi Float ctermfg=69 ctermbg=NONE cterm=NONE
  hi Function ctermfg=203 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=221 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=230 ctermbg=NONE cterm=NONE
  hi Include ctermfg=203 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=214 ctermbg=NONE cterm=NONE
  hi Label ctermfg=203 ctermbg=NONE cterm=NONE
  hi Number ctermfg=69 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=230 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=117 ctermbg=NONE cterm=NONE
  hi Special ctermfg=117 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=117 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=203 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=214 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=214 ctermbg=NONE cterm=NONE
  hi String ctermfg=69 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=203 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=117 ctermbg=NONE cterm=bold
  hi Type ctermfg=177 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=230 cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=236 cterm=NONE
  hi ToolbarButton ctermfg=214 ctermbg=236 cterm=bold
  hi NormalMode ctermfg=102 ctermbg=230 cterm=reverse
  hi InsertMode ctermfg=69 ctermbg=234 cterm=reverse
  hi ReplaceMode ctermfg=203 ctermbg=234 cterm=reverse
  hi VisualMode ctermfg=214 ctermbg=230 cterm=reverse
  hi CommandMode ctermfg=117 ctermbg=230 cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=230 ctermbg=102 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'wwdc16_transp_bg', 0)
    hi Normal ctermfg=White ctermbg=NONE cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=Black ctermbg=NONE cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=White ctermbg=NONE cterm=NONE
  else
    hi Normal ctermfg=White ctermbg=Black cterm=NONE
    hi CursorLineNr ctermfg=White ctermbg=Black cterm=NONE
    hi FoldColumn ctermfg=Gray ctermbg=Black cterm=NONE
    hi LineNr ctermfg=Gray ctermbg=Black cterm=NONE
    hi Terminal ctermfg=White ctermbg=Black cterm=NONE
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi Conceal ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=White cterm=NONE
  hi CursorColumn ctermfg=NONE ctermbg=Black cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi DiffAdd ctermfg=LightGreen ctermbg=White cterm=reverse
  hi DiffChange ctermfg=Blue ctermbg=White cterm=reverse
  hi DiffDelete ctermfg=Red ctermbg=White cterm=reverse
  hi DiffText ctermfg=Red ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=Blue ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Black ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=Red ctermbg=White cterm=reverse
  hi Folded ctermfg=Gray ctermbg=Black cterm=italic
  hi IncSearch ctermfg=LightBlue ctermbg=White cterm=reverse
  hi MatchParen ctermfg=Black ctermbg=DarkCyan cterm=bold,reverse
  hi ModeMsg ctermfg=White ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Gray ctermbg=NONE cterm=NONE
  hi NonText ctermfg=White ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi PmenuSbar ctermfg=Black ctermbg=Black cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi PmenuThumb ctermfg=Black ctermbg=DarkCyan cterm=NONE
  hi Question ctermfg=Gray ctermbg=NONE cterm=NONE
  hi Search ctermfg=DarkCyan ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Gray ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=Red ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=Red ctermbg=NONE cterm=underline
  hi StatusLine ctermfg=DarkRed ctermbg=White cterm=reverse
  hi StatusLineNC ctermfg=DarkRed ctermbg=White cterm=reverse
  hi TabLine ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=DarkRed cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=DarkRed cterm=NONE
  hi Title ctermfg=White ctermbg=NONE cterm=bold
  hi VertSplit ctermfg=Black ctermbg=DarkRed cterm=NONE
  hi Visual ctermfg=White ctermbg=DarkCyan cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkCyan cterm=NONE
  hi WarningMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=LightBlue cterm=NONE
  hi Boolean ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Character ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Comment ctermfg=Gray ctermbg=NONE cterm=italic
  hi Constant ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Debug ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=White ctermbg=NONE cterm=NONE
  hi Error ctermfg=Red ctermbg=White cterm=reverse
  hi Float ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Function ctermfg=Red ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=Yellow ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=White ctermbg=NONE cterm=NONE
  hi Include ctermfg=Red ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Label ctermfg=Red ctermbg=NONE cterm=NONE
  hi Number ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Operator ctermfg=White ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi Special ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=LightBlue ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=Red ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi String ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Structure ctermfg=Red ctermbg=NONE cterm=NONE
  hi Todo ctermfg=LightBlue ctermbg=NONE cterm=bold
  hi Type ctermfg=LightMagenta ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi ToolbarLine ctermfg=NONE ctermbg=Black cterm=NONE
  hi ToolbarButton ctermfg=DarkRed ctermbg=Black cterm=bold
  hi NormalMode ctermfg=Gray ctermbg=White cterm=reverse
  hi InsertMode ctermfg=Blue ctermbg=Black cterm=reverse
  hi ReplaceMode ctermfg=Red ctermbg=Black cterm=reverse
  hi VisualMode ctermfg=DarkRed ctermbg=White cterm=reverse
  hi CommandMode ctermfg=LightBlue ctermbg=White cterm=reverse
  if !s:italics
    hi Folded cterm=NONE
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=White ctermbg=Gray cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

" Background: dark
" Color: base00 #1f1f1f ~ Black # Default Background
" Color: base01 #353535 ~ Black # Lighter Background (Used for status bars, line number and folding marks)
" Color: base02 #356575 ~ DarkCyan # Selection Background
" Color: base03 #858585 ~ Gray # Comments, Invisibles, Line Highlighting
" Color: base04 #eae7cd ~ White # Dark Foreground (Used for status bars)
" Color: base05 #faf1d4 ~ White # Default Foreground, Caret, Delimiters, Operators
" Color: base06 #faf1d4 ~ White # Light Foreground (Not often used)
" Color: base07 #faf1d4 ~ White # Light Background (Not often used)
" Color: base08 #f5da71 ~ Yellow # Variables, XML Tags, Markup Link Text, Markup Lists, Diff Deleted
" Color: base09 #6e7bfa ~ Blue # Integers, Boolean, Constants, XML Attributes, Markup Link Url
" Color: base0A #df85ff ~ LightMagenta # Classes, Markup Bold, Search Text Background
" Color: base0B #bede48 ~ LightGreen # Strings, Inherited Class, Markup Code, Diff Inserted
" Color: base0C #9fdfff ~ LightBlue # Support, Regular Expressions, Escape Characters, Markup Quotes
" Color: base0D #fa755f ~ Red # Functions, Methods, Attribute IDs, Headings
" Color: base0E #ffc145 ~ DarkRed # Keywords, Storage, Selector, Markup Italic, Diff Changed
" Color: base0F #ab7967 ~ Cyan # Deprecated, Opening/Closing Embedded Language Tags, e.g. <?php ?>
" Term Colors: base00 base0D base0D base0E base09 base0C base0E base03
" Term Colors: base01 base0D base09 base08
" Term Colors: base09 base0A base0C base05
" vim: et ts=2 sw=2
